import io
import os
import zipfile
import base64
from typing import Dict, Any, Tuple
from app.schemas import FullSchema

def generate_db_ddl(schemas: FullSchema) -> str:
    """Generates PostgreSQL DDL schema string."""
    ddl = "-- Database Schema Generated by AppForge AI\n\n"
    for table in schemas.db.tables:
        ddl += f"CREATE TABLE IF NOT EXISTS {table.name} (\n"
        cols = []
        for col in table.columns:
            col_str = f"    {col.name} "
            if col.type == "integer":
                col_str += "SERIAL" if col.primary_key else "INTEGER"
            elif col.type == "string":
                col_str += "VARCHAR(255)"
            elif col.type == "boolean":
                col_str += "BOOLEAN"
            elif col.type == "datetime":
                col_str += "TIMESTAMP"
            elif col.type == "float":
                col_str += "DOUBLE PRECISION"
            elif col.type == "text":
                col_str += "TEXT"
            else:
                col_str += "VARCHAR(255)"
            
            if not col.nullable:
                col_str += " NOT NULL"
            
            if col.primary_key:
                col_str += " PRIMARY KEY"
            elif col.foreign_key:
                fk_parts = col.foreign_key.split(".")
                if len(fk_parts) == 2:
                    col_str += f" REFERENCES {fk_parts[0]}({fk_parts[1]})"
                else:
                    col_str += f" REFERENCES {col.foreign_key}"
            
            cols.append(col_str)
        ddl += ",\n".join(cols)
        ddl += "\n);\n\n"
    return ddl

def generate_sqlalchemy_models(schemas: FullSchema) -> str:
    """Generates SQLAlchemy models string."""
    code = """# SQLAlchemy Database Models mapping the database schema
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
import datetime

Base = declarative_base()
"""
    for table in schemas.db.tables:
        model_name = table.name.capitalize()
        # singularize model name
        if model_name.endswith("s"):
            model_name = model_name[:-1]
            
        code += f"\nclass {model_name}(Base):\n"
        code += f"    __tablename__ = '{table.name}'\n\n"
        for col in table.columns:
            col_type = "String"
            if col.type == "integer":
                col_type = "Integer"
            elif col.type == "boolean":
                col_type = "Boolean"
            elif col.type == "datetime":
                col_type = "DateTime"
            elif col.type == "float":
                col_type = "Float"
            elif col.type == "text":
                col_type = "Text"
            
            col_params = []
            if col.primary_key:
                col_params.append("primary_key=True")
            if not col.nullable:
                col_params.append("nullable=False")
            if col.foreign_key:
                col_params.append(f"ForeignKey('{col.foreign_key}')")
                
            params_str = ", ".join(col_params)
            params_str = f", {params_str}" if params_str else ""
            
            code += f"    {col.name} = Column({col_type}{params_str})\n"
            
    return code

def generate_fastapi_main(schemas: FullSchema) -> str:
    """Generates FastAPI app main.py file."""
    endpoints_code = ""
    for ep in schemas.api.endpoints:
        path = ep.path
        method = ep.method.lower()
        desc = ep.description
        
        # Skip custom implemented auth endpoints in loop
        if path in ["/api/auth/login", "/api/auth/signup"]:
            continue
            
        # Determine python function name
        func_name = ep.path.strip("/").replace("/", "_").replace("{", "").replace("}", "")
        func_name = f"{method}_{func_name}" if func_name else f"{method}_root"
        
        dep_str = ""
        if "login" not in path.lower() and "signup" not in path.lower():
            dep_str = ", current_user: dict = Depends(get_current_active_user)"
            
        endpoints_code += f"""
@app.{method}("{path}", summary="{desc}")
async def {func_name}(body: dict = None{dep_str}):
    # Business logic rules execution
    # Permissions check based on Auth rules
    return {{"status": "success", "message": "Endpoint executed successfully", "data": body}}
"""

    main_code = f"""# FastAPI application entrypoint
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from typing import List
from jose import JWTError, jwt
from datetime import datetime, timedelta
from sqlalchemy.orm import Session

from app.database import init_db, get_db
from app.models import User
from app.auth import get_password_hash, verify_password, create_access_token

# Initialize SQLite database and tables on startup
init_db()

app = FastAPI(
    title="AppForge AI Generated Application",
    description="This application was generated by AppForge AI Compiler.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

async def get_current_active_user():
    # Placeholder for JWT parsing & Role validation
    return {{"email": "user@example.com", "role": "admin"}}

@app.get("/")
async def root():
    return {{"name": "AppForge AI Generated API", "version": "1.0.0", "status": "healthy"}}

@app.post("/api/auth/signup", summary="Sign up a new user")
async def post_api_auth_signup(body: dict = None, db: Session = Depends(get_db)):
    if not body or "email" not in body or "password" not in body:
        raise HTTPException(status_code=400, detail="Email and password required")
    existing = db.query(User).filter(User.email == body["email"]).first()
    if existing:
        raise HTTPException(status_code=400, detail="User already registered")
    
    hashed = get_password_hash(body["password"])
    user = User(email=body["email"], hashed_password=hashed, role=body.get("role", "customer"))
    db.add(user)
    db.commit()
    db.refresh(user)
    return {{"status": "success", "user_id": user.id}}

@app.post("/api/auth/login", summary="Authenticate user credentials")
async def post_api_auth_login(body: dict = None, db: Session = Depends(get_db)):
    if not body or "email" not in body or "password" not in body:
        raise HTTPException(status_code=400, detail="Email and password required")
    user = db.query(User).filter(User.email == body["email"]).first()
    if not user or not verify_password(body["password"], user.hashed_password):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    token = create_access_token(data={{"sub": user.email, "role": user.role}})
    return {{"access_token": token, "token_type": "bearer", "role": user.role}}

{endpoints_code}
"""
    return main_code

def generate_frontend_navbar(schemas: FullSchema) -> str:
    links = []
    for page in schemas.ui.pages:
        links.append(f"{{ name: '{page.name}', href: '{page.route}' }}")
        
    code = f"""import Link from 'next/link';
import {{ useRouter }} from 'next/router';

export default function Navbar() {{
  const router = useRouter();
  const links = [
    {", ".join(links)}
  ];

  return (
    <nav className="bg-zinc-950 border-b border-zinc-800 text-white py-4 px-8 flex justify-between items-center">
      <div className="text-xl font-bold tracking-tight text-emerald-400">AppForge Generated App</div>
      <div className="flex space-x-6">
        {{links.map((link) => (
          <Link
            key={{link.href}}
            href={{link.href}}
            className={{`hover:text-emerald-400 transition-colors ${{
              router.pathname === link.href ? 'text-emerald-400 font-semibold' : 'text-zinc-400'
            }}`}}
          >
            {{link.name}}
          </Link>
        ))}}
      </div>
      <div>
        <button className="bg-emerald-500 hover:bg-emerald-600 text-zinc-950 font-semibold px-4 py-2 rounded-md text-sm transition-all">
          Logout
        </button>
      </div>
    </nav>
  );
}}
"""
    return code

def generate_frontend_page(page: UIPage) -> str:
    components_code = ""
    for comp in page.components:
        if comp.type == "card":
            metrics = comp.props.get("metrics", ["KPI Value"])
            components_code += f"""
        {{"/* Stats Summary Widget */"}}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {{" "}}
          {metrics.__repr__()}.map((metric) => (
            <div key={{metric}} className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl backdrop-blur-md">
              <div className="text-zinc-500 text-sm font-medium">{{metric}}</div>
              <div className="text-3xl font-bold mt-2 text-white">1,248</div>
              <div className="text-emerald-500 text-xs mt-1 font-semibold">↑ 12% vs last month</div>
            </div>
          ))
        </div>
"""
        elif comp.type == "table":
            headers = comp.props.get("headers", ["Column"])
            headers_th = "\n".join([f'                  <th className="px-6 py-3 text-left text-xs font-semibold text-zinc-400 uppercase tracking-wider">{h}</th>' for h in headers])
            components_code += f"""
        {{"/* Data Table Widget */"}}
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden mb-8">
          <div className="p-5 border-b border-zinc-800 flex justify-between items-center">
            <h3 className="text-lg font-semibold text-white">{comp.name.replace('_', ' ').capitalize()}</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-zinc-800">
              <thead className="bg-zinc-950">
                <tr>
{headers_th}
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800 text-sm text-zinc-300">
                <tr>
                  {", ".join([f'<td className="px-6 py-4">Sample {h} Data</td>' for h in headers])}
                </tr>
                <tr>
                  {", ".join([f'<td className="px-6 py-4">Another {h} Data</td>' for h in headers])}
                </tr>
              </tbody>
            </table>
          </div>
        </div>
"""
        elif comp.type == "form":
            fields = comp.props.get("fields", ["name"])
            submit_label = comp.props.get("submit_label", "Submit")
            form_fields = ""
            for f in fields:
                form_fields += f"""
            <div className="mb-4">
              <label className="block text-sm font-medium text-zinc-400 mb-1 capitalize">{f.replace('_', ' ')}</label>
              <input type="text" className="w-full bg-zinc-950 border border-zinc-800 rounded-md p-2 text-white focus:outline-none focus:border-emerald-500 text-sm" placeholder="Enter {f}" />
            </div>
"""
            components_code += f"""
        {{"/* Form Widget */"}}
        <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl mb-8 max-w-xl">
          <h3 className="text-lg font-semibold text-white mb-4">{comp.name.replace('_', ' ').capitalize()}</h3>
          <form onSubmit={{(e) => e.preventDefault()}}>
{form_fields}
            <button className="bg-emerald-500 hover:bg-emerald-600 text-zinc-950 font-bold px-4 py-2 rounded-md text-sm w-full transition-all">
              {submit_label}
            </button>
          </form>
        </div>
"""
        elif comp.type == "chart":
            components_code += f"""
        {{"/* Chart Widget */"}}
        <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl mb-8">
          <h3 className="text-lg font-semibold text-white mb-2">{comp.name.replace('_', ' ').capitalize()}</h3>
          <div className="h-64 bg-zinc-950/50 border border-zinc-800 border-dashed rounded-lg flex items-center justify-center">
            <span className="text-zinc-600 text-sm">Interactive [{comp.props.get('chart_type', 'bar')}] chart data visual</span>
          </div>
        </div>
"""
            
    code = f"""import React from 'react';
import Navbar from '../components/Navbar';

export default function {page.name}Page() {{
  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <Navbar />
      <main className="max-w-7xl mx-auto py-8 px-6">
        <h1 className="text-3xl font-extrabold tracking-tight mb-2 text-white">{page.name}</h1>
        <p className="text-zinc-400 text-sm mb-8">Generated dynamic page view.</p>
{components_code}
      </main>
    </div>
  );
}}
"""
    return code

def generate_project_zip(schemas: FullSchema) -> Tuple[bytes, Dict[str, Any]]:
    """Compiles all code files and wraps them into a ZIP archive, returning the raw bytes and a file tree representation."""
    zip_buffer = io.BytesIO()
    
    # Files dictionary to track generated files for the explorer
    files = {}

    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        # 1. Database SQL
        ddl = generate_db_ddl(schemas)
        zip_file.writestr("database/schema.sql", ddl)
        files["database/schema.sql"] = ddl

        # 2. Backend FastAPI
        reqs = "fastapi>=0.111.0\nuvicorn>=0.30.1\nsqlalchemy>=2.0.30\npython-jose[cryptography]>=3.3.0\npasslib[bcrypt]>=1.7.4\n"
        zip_file.writestr("backend/requirements.txt", reqs)
        files["backend/requirements.txt"] = reqs

        main_py = generate_fastapi_main(schemas)
        zip_file.writestr("backend/app/main.py", main_py)
        files["backend/app/main.py"] = main_py

        models_py = generate_sqlalchemy_models(schemas)
        zip_file.writestr("backend/app/models.py", models_py)
        files["backend/app/models.py"] = models_py

        auth_py = """# Authentication & JWT security utilities
from jose import JWTError, jwt
from passlib.context import CryptContext
from datetime import datetime, timedelta

SECRET_KEY = "SUPER_SECRET_APPFORGE_KEY_CHANGE_IN_PRODUCTION"
ALGORITHM = "HS256"

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def verify_password(plain_password, hashed_password):
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password):
    return pwd_context.hash(password)

def create_access_token(data: dict, expires_delta: timedelta = None):
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=15))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
"""
        zip_file.writestr("backend/app/auth.py", auth_py)
        files["backend/app/auth.py"] = auth_py

        database_py = """# Database setup and session connection
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.models import Base

SQLALCHEMY_DATABASE_URL = "sqlite:///./appforge.db"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def init_db():
    Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
"""
        zip_file.writestr("backend/app/database.py", database_py)
        files["backend/app/database.py"] = database_py

        # 3. Frontend Next.js
        pkg_json = """{
  "name": "appforge-generated-next",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "lucide-react": "^0.450.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/react": "^19.0.0",
    "tailwindcss": "^3.4.0",
    "autoprefixer": "^10.0.0",
    "postcss": "^8.0.0"
  }
}"""
        zip_file.writestr("frontend/package.json", pkg_json)
        files["frontend/package.json"] = pkg_json

        navbar_tsx = generate_frontend_navbar(schemas)
        zip_file.writestr("frontend/components/Navbar.tsx", navbar_tsx)
        files["frontend/components/Navbar.tsx"] = navbar_tsx

        # Render Pages
        app_tsx = """import "@/styles/globals.css";
import type { AppProps } from "next/app";

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}"""
        zip_file.writestr("frontend/pages/_app.tsx", app_tsx)
        files["frontend/pages/_app.tsx"] = app_tsx

        for page in schemas.ui.pages:
            pcode = generate_frontend_page(page)
            filename = f"frontend/pages/{page.name.lower()}.tsx"
            # Dashboard is index
            if page.name.lower() == "dashboard":
                filename = "frontend/pages/index.tsx"
            zip_file.writestr(filename, pcode)
            files[filename] = pcode

        # 4. README documentation
        readme = f"""# AppForge AI Generated Application

This application package was dynamically generated from natural language specifications.

## Project Structure
- `backend/`: FastAPI Python server with mock routes and security filters.
- `frontend/`: Next.js pages router application utilizing Tailwind styling.
- `database/`: Raw DDL file for PostgreSQL schema setup.

## Setup Instructions

### Backend
1. Navigate to `/backend`
2. Create virtual environment: `python -m venv .venv`
3. Activate it: `.venv\\Scripts\\activate` (Windows) or `source .venv/bin/activate` (Mac/Linux)
4. Install packages: `pip install -r requirements.txt`
5. Run server: `uvicorn app.main:app --reload`

### Frontend
1. Navigate to `/frontend`
2. Install npm modules: `npm install`
3. Run compiler project local web server: `npm run dev`

### Database
1. Run DDL schema in target PostgreSQL instance: `psql -d <db_name> -f database/schema.sql`
"""
        zip_file.writestr("README.md", readme)
        files["README.md"] = readme

    # Format files into a clean nested tree for the UI explorer
    file_tree = {}
    for filepath in files.keys():
        parts = filepath.split("/")
        current = file_tree
        for part in parts[:-1]:
            if part not in current:
                current[part] = {}
            current = current[part]
        current[parts[-1]] = filepath # Leaves store the full key path

    return zip_buffer.getvalue(), {"tree": file_tree, "contents": files}

# Mock records data for interactive UI previewing
def generate_preview_data(schemas: FullSchema) -> Dict[str, Any]:
    preview = {"pages": [], "records": {}}
    for page in schemas.ui.pages:
        p_data = {
            "name": page.name,
            "route": page.route,
            "components": []
        }
        for comp in page.components:
            p_data["components"].append({
                "name": comp.name,
                "type": comp.type,
                "props": comp.props
            })
        preview["pages"].append(p_data)
    
    # Add dummy dataset for lists/tables preview
    for table in schemas.db.tables:
        t_name = table.name.lower()
        if t_name == "users":
            preview["records"][t_name] = [
                {"id": 1, "email": "admin@appforge.io", "role": "admin"},
                {"id": 2, "email": "agent@appforge.io", "role": "sales_agent"},
                {"id": 3, "email": "client@appforge.io", "role": "customer"}
            ]
        elif "contact" in t_name:
            preview["records"][t_name] = [
                {"id": 1, "first_name": "Elon", "last_name": "Musk", "email": "elon@tesla.com", "phone": "555-1234", "status": "active"},
                {"id": 2, "first_name": "Satya", "last_name": "Nadella", "email": "satya@microsoft.com", "phone": "555-5678", "status": "lead"},
                {"id": 3, "first_name": "Tim", "last_name": "Cook", "email": "tim@apple.com", "phone": "555-9012", "status": "inactive"}
            ]
        elif "deal" in t_name:
            preview["records"][t_name] = [
                {"id": 1, "title": "Tesla Fleet Order", "value": 150000.0, "stage": "proposal"},
                {"id": 2, "title": "Azure Migration Contract", "value": 450000.0, "stage": "negotiation"},
                {"id": 3, "title": "iPhone Enterprise Deal", "value": 95000.0, "stage": "closed_won"}
            ]
        elif "subscription" in t_name or "billing" in t_name:
            preview["records"][t_name] = [
                {"id": 1, "user_id": 3, "plan_id": "pro", "status": "active"}
            ]
        else:
            preview["records"][t_name] = [
                {"id": 1, "name": f"Mock {table.name} 1", "created_at": "2026-06-04T12:00:00Z"},
                {"id": 2, "name": f"Mock {table.name} 2", "created_at": "2026-06-04T14:30:00Z"}
            ]
    return preview
